import {
  NotificationItem,
  Campaign,
  Template,
  UserItem,
  Vehicle,
  MakeAlert,
  ModelAlert,
  AutomationRule,
  QueueJob,
  DashboardStats,
  ChartDataPoint,
} from "@/types";

export const MOCK_STATS: DashboardStats = {
  totalSent: 45892,
  delivered: 44102,
  opened: 18765,
  failed: 231,
  pendingQueue: 3,
  registeredDevices: 9482,
  activeUsers: 14210,
  newArrivalsSent: 3420,
  deliveryRate: 96.1,
  openRate: 42.5,
  failureRate: 0.5,
  sentTrend: 12.4,
  deliveredTrend: 11.8,
  openedTrend: 8.2,
  failedTrend: -4.3,
};

export const MOCK_CHART_DATA: Record<string, ChartDataPoint[]> = {
  "7d": [
    { date: "Mon", sent: 3200, delivered: 3100, opened: 1420, failed: 15 },
    { date: "Tue", sent: 4100, delivered: 3950, opened: 1890, failed: 22 },
    { date: "Wed", sent: 2800, delivered: 2710, opened: 1150, failed: 12 },
    { date: "Thu", sent: 5400, delivered: 5200, opened: 2450, failed: 35 },
    { date: "Fri", sent: 6200, delivered: 5980, opened: 2890, failed: 28 },
    { date: "Sat", sent: 4900, delivered: 4750, opened: 2100, failed: 19 },
    { date: "Sun", sent: 5800, delivered: 5610, opened: 2540, failed: 24 },
  ],
  "30d": [
    { date: "Aug 1", sent: 4200, delivered: 4050, opened: 1720, failed: 25 },
    { date: "Aug 5", sent: 5100, delivered: 4900, opened: 2100, failed: 30 },
    { date: "Aug 10", sent: 6400, delivered: 6150, opened: 2750, failed: 40 },
    { date: "Aug 15", sent: 5800, delivered: 5600, opened: 2400, failed: 32 },
    { date: "Aug 20", sent: 7200, delivered: 6950, opened: 3100, failed: 45 },
    { date: "Aug 25", sent: 6800, delivered: 6550, opened: 2900, failed: 38 },
    { date: "Aug 30", sent: 7500, delivered: 7250, opened: 3300, failed: 42 },
  ],
  "90d": [
    { date: "Jun 1", sent: 68000, delivered: 65400, opened: 27800, failed: 420 },
    { date: "Jul 1", sent: 74500, delivered: 71800, opened: 31200, failed: 390 },
    { date: "Aug 1", sent: 82100, delivered: 79200, opened: 35100, failed: 410 },
  ],
};

export const MOCK_NOTIFICATIONS: NotificationItem[] = [
  {
    id: "1",
    title: "Price Drop Alert: 2023 Honda Civic RS!",
    message: "Great news! The price of 2023 Honda Civic RS dropped by ฿50,000. Check it out now!",
    translations: {
      en: {
        title: "Price Drop Alert: 2023 Honda Civic RS!",
        message: "Great news! The price of 2023 Honda Civic RS dropped by ฿50,000. Check it out now!",
      },
      th: {
        title: "ปรับลดราคา! Honda Civic RS ปี 2023",
        message: "ข่าวดี! ราคาของ Honda Civic RS ปี 2023 ลดลง 50,000 บาท เข้าชมเลยตอนนี้!",
      },
      zh: {
        title: "降价提醒：2023 本田 Civic RS！",
        message: "好消息！2023 本田 Civic RS 的价格已降低 ฿50,000。立即查看！",
      },
    },
    type: "price_drop",
    audience: "Favourite Followers (420 Users)",
    audienceType: "specific_users",
    targetLanguages: ["en", "th", "zh"],
    status: "delivered",
    sentCount: 420,
    deliveredCount: 412,
    openedCount: 238,
    failedCount: 2,
    created: "2026-08-13 14:20",
    sentAt: "2026-08-13 14:21",
    createdBy: "Admin System (Automated)",
    actionType: "vehicle",
    actionPayload: { type: "car_detail", listing_id: "51962" },
    imageUrl: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop&q=80",
    listingId: "51962",
    oneSignalId: "os-8a21f-994012",
  },
  {
    id: "2",
    title: "New Arrival: 2024 Mercedes-Benz C220d AMG Line",
    message: "Just listed! Pristine condition Mercedes C-Class with low mileage. Inspect photos today.",
    translations: {
      en: {
        title: "New Arrival: 2024 Mercedes-Benz C220d AMG Line",
        message: "Just listed! Pristine condition Mercedes C-Class with low mileage. Inspect photos today.",
      },
      th: {
        title: "รถเข้าใหม่: Mercedes-Benz C220d AMG Line ปี 2024",
        message: "เพิ่งลงขาย! รถเบนซ์ C-Class สภาพนางฟ้า ไมล์น้อย ดูรูปถ่ายได้แล้ววันนี้",
      },
      zh: {
        title: "新车到港：2024 梅赛德斯-奔驰 C220d AMG Line",
        message: "刚上架！全新状态奔驰 C 级，低里程。立即查看照片。",
      },
    },
    type: "new_arrival",
    audience: "All Users (9,482 Devices)",
    audienceType: "all",
    targetLanguages: ["en", "th", "zh"],
    status: "delivered",
    sentCount: 9482,
    deliveredCount: 9210,
    openedCount: 4120,
    failedCount: 45,
    created: "2026-08-13 11:00",
    sentAt: "2026-08-13 11:01",
    createdBy: "Somchai (Operations)",
    actionType: "vehicle",
    actionPayload: { type: "car_detail", listing_id: "51980" },
    imageUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80",
    listingId: "51980",
    oneSignalId: "os-3b88a-772109",
  },
  {
    id: "3",
    title: "Mid-Year WowCar Trade-In Special Promotion!",
    message: "Get up to ฿100,000 bonus value when you sell or trade in your car this weekend at WowCar.",
    translations: {
      en: {
        title: "Mid-Year WowCar Trade-In Special Promotion!",
        message: "Get up to ฿100,000 bonus value when you sell or trade in your car this weekend at WowCar.",
      },
      th: {
        title: "โปรโมชั่นพิเศษ! เทิร์นรถรับโบนัสสูงสุด 100,000 บาท",
        message: "รับข้อเสนอสุดคุ้มกลางปีเมื่อนำรถมาขายหรือเทิร์นที่ WowCar สุดสัปดาห์นี้!",
      },
      zh: {
        title: "WowCar 年中以旧换新特别优惠！",
        message: "本周末在 WowCar 出售或置换您的爱车，最高可获得 ฿100,000 额外补贴。",
      },
    },
    type: "promotion",
    audience: "Registered Devices (9,482)",
    audienceType: "registered_devices",
    targetLanguages: ["en", "th", "zh"],
    status: "delivered",
    sentCount: 9482,
    deliveredCount: 9140,
    openedCount: 3890,
    failedCount: 52,
    created: "2026-08-12 16:30",
    sentAt: "2026-08-12 16:35",
    createdBy: "Marketing Lead",
    actionType: "buy_car",
    actionPayload: { type: "promotion_page", promo_code: "MIDYEAR2026" },
    imageUrl: "https://images.unsplash.com/photo-1563720223185-11003d516935?w=800&auto=format&fit=crop&q=80",
    oneSignalId: "os-1c99f-440129",
  },
  {
    id: "4",
    title: "New Toyota Vehicles Restocked",
    message: "15 new Toyota Fortuner and Yaris Ativ units added to our listings today.",
    translations: {
      en: {
        title: "New Toyota Vehicles Restocked",
        message: "15 new Toyota Fortuner and Yaris Ativ units added to our listings today.",
      },
      th: {
        title: "อัปเดตรถเข้าใหม่! Toyota Fortuner และ Yaris Ativ",
        message: "มีรถ Toyota เข้าใหม่ 15 คัน รวมถึง Fortuner และ Yaris Ativ พร้อมเช็คประวัติได้แล้ว",
      },
      zh: {
        title: "全新丰田车源上架",
        message: "今日新增 15 台全新丰田 Fortuner 和 Yaris Ativ 车源。",
      },
    },
    type: "vehicle_notification",
    audience: "Toyota Model Followers (923 Users)",
    audienceType: "make_followers",
    targetLanguages: ["en", "th"],
    status: "delivered",
    sentCount: 923,
    deliveredCount: 905,
    openedCount: 450,
    failedCount: 4,
    created: "2026-08-11 10:15",
    sentAt: "2026-08-11 10:20",
    createdBy: "Automated Rule #4",
    actionType: "search",
    actionPayload: { make: "Toyota" },
    oneSignalId: "os-77f2c-120034",
  },
  {
    id: "5",
    title: "Scheduled Maintenance Notification",
    message: "The WowCar mobile app will undergo routine server upgrades tonight at 02:00 AM ICT.",
    translations: {
      en: {
        title: "Scheduled Maintenance Notification",
        message: "The WowCar mobile app will undergo routine server upgrades tonight at 02:00 AM ICT.",
      },
      th: {
        title: "แจ้งปิดปรับปรุงระบบชั่วคราว",
        message: "ระบบจะทำการอัปเกรดเซิร์ฟเวอร์ในคืนนี้ เวลา 02:00 น. ขออภัยในความไม่สะดวก",
      },
      zh: {
        title: "例行维护通知",
        message: "WowCar 移动 App 将于今晚 02:00 (ICT) 进行例行服务器升级。",
      },
    },
    type: "general_announcement",
    audience: "All Active App Users",
    audienceType: "all",
    targetLanguages: ["en", "th", "zh"],
    status: "scheduled",
    sentCount: 0,
    deliveredCount: 0,
    openedCount: 0,
    failedCount: 0,
    created: "2026-08-13 15:00",
    scheduledAt: "2026-08-13 23:30",
    createdBy: "DevOps Admin",
    actionType: "inbox",
  },
];

export const MOCK_CAMPAIGNS: Campaign[] = [
  {
    id: "1",
    name: "Weekend Flash Sales Blitz",
    type: "promotion",
    audience: "All Registered Devices",
    status: "completed",
    sent: 9480,
    delivered: 9210,
    opened: 4150,
    ctr: "45.1%",
    scheduledDate: "2026-08-10 10:00",
    createdBy: "Sarah Admin",
  },
  {
    id: "2",
    name: "Luxury Sedan Spotlight - August",
    type: "vehicle_notification",
    audience: "BMW & Mercedes Followers",
    status: "sending",
    sent: 1580,
    delivered: 1510,
    opened: 680,
    ctr: "45.0%",
    scheduledDate: "2026-08-13 16:00",
    createdBy: "Marketing Lead",
  },
  {
    id: "3",
    name: "EV & Hybrid Buyers Campaign",
    type: "new_arrival",
    audience: "BYD & Tesla Interested Users",
    status: "scheduled",
    sent: 0,
    delivered: 0,
    opened: 0,
    ctr: "0%",
    scheduledDate: "2026-08-15 09:00",
    createdBy: "Nattapon (Sales)",
  },
  {
    id: "4",
    name: "Q3 Buyer Retention Re-engagement",
    type: "general_announcement",
    audience: "Inactive (>30 days)",
    status: "draft",
    sent: 0,
    delivered: 0,
    opened: 0,
    ctr: "0%",
    scheduledDate: "—",
    createdBy: "Sarah Admin",
  },
];

export const MOCK_TEMPLATES: Template[] = [
  {
    id: "1",
    name: "New Vehicle Arrival Alert",
    type: "new_arrival",
    translations: {
      en: {
        title: "Just In: {vehicle_title} is Now Available!",
        message: "Check out this fresh listing for {price}. Tap to view full specs and inspection report.",
      },
      th: {
        title: "มาใหม่! {vehicle_title} พร้อมให้คุณเป็นเจ้าของแล้ว",
        message: "เปิดตัวรถเข้าใหม่ราคา {price} ดูสเปกฉบับเต็มและผลตรวจสภาพได้เลย",
      },
      zh: {
        title: "新车到港：{vehicle_title} 现已发售！",
        message: "查看最新上架车源，售价 {price}。点击查看完整配置与检测报告。",
      },
    },
    destinationType: "vehicle",
    defaultImageBehavior: "vehicle",
  },
  {
    id: "2",
    name: "Price Drop Notification",
    type: "price_drop",
    translations: {
      en: {
        title: "Price Reduced on {vehicle_title}!",
        message: "Good news! A car in your saved list just dropped by {discount_amount}. Don't miss out!",
      },
      th: {
        title: "ลดราคาแล้ว! {vehicle_title}",
        message: "ข่าวดี! รถที่คุณถูกใจปรับลดราคาลง {discount_amount} รีบดูรายละเอียดก่อนใคร",
      },
      zh: {
        title: "{vehicle_title} 降价通知！",
        message: "好消息！您收藏的车辆已降价 {discount_amount}。切勿错过！",
      },
    },
    destinationType: "vehicle",
    defaultImageBehavior: "vehicle",
  },
  {
    id: "3",
    name: "Seasonal Special Promotion",
    type: "promotion",
    translations: {
      en: {
        title: "Exclusive WowCar Bonus Offer Inside!",
        message: "Enjoy special financing interest rates starting at 1.99% for select cars this month.",
      },
      th: {
        title: "สิทธิพิเศษจาก WowCar ดอกเบี้ยเริ่มต้น 1.99%",
        message: "รับข้อเสนอพิเศษสำหรับการจัดไฟแนนซ์รถยนต์ประจำเดือนนี้ คลิกเพื่อดูเงื่อนไข",
      },
      zh: {
        title: "WowCar 专属季末特别优惠！",
        message: "本月精选车源享有低至 1.99% 的金融利率特惠。",
      },
    },
    destinationType: "buy_car",
    defaultImageBehavior: "custom",
  },
];

export const MOCK_USERS: UserItem[] = [
  {
    wpUserId: "10482",
    name: "Kittisak Prasert",
    email: "kittisak.p@gmail.com",
    language: "th",
    platform: "iOS",
    registeredDevices: 2,
    pushEnabled: true,
    lastSeen: "2 mins ago",
    priceDropAlerts: true,
    newArrivalAlerts: true,
    oneSignalExternalId: "usr_os_8829104",
  },
  {
    wpUserId: "10483",
    name: "John Miller",
    email: "john.miller@expats-bkk.com",
    language: "en",
    platform: "Android",
    registeredDevices: 1,
    pushEnabled: true,
    lastSeen: "1 hour ago",
    priceDropAlerts: true,
    newArrivalAlerts: false,
    oneSignalExternalId: "usr_os_3349122",
  },
  {
    wpUserId: "10484",
    name: "Chen Wei",
    email: "chenwei.bkk@qq.com",
    language: "zh",
    platform: "iOS",
    registeredDevices: 1,
    pushEnabled: true,
    lastSeen: "Yesterday",
    priceDropAlerts: true,
    newArrivalAlerts: true,
    oneSignalExternalId: "usr_os_5520194",
  },
];


export const MOCK_VEHICLES: Vehicle[] = [
  {
    listingId: "51962",
    title: "2023 Honda Civic 1.5 RS Turbo",
    make: "Honda",
    model: "Civic",
    price: 989000,
    formattedPrice: "฿989,000",
    oldPrice: 1039000,
    dealerPrice: 950000,
    status: "Publish",
    publishedDate: "2026-08-10",
    imageUrl: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop&q=80",
    featured: true,
    featuredExpire: "2026-12-31",
    referenceCode: "REF-2026-99",
    year: 2023,
    mileage: 35000,
    modelSpecific: "1.5 RS Turbo Sedan",
    bodyStyle: "Sedan",
    fuelType: "Gasoline",
    transmission: "Automatic",
    drivetrain: "FWD",
    color: "White",
    engineSize: "1.5L",
    doorCount: "4",
    safetyFeatures: ["ABS", "Airbags", "Lane Assist", "Blind Spot Monitor"],
    comfortFeatures: ["Leather Seats", "Sunroof", "Apple CarPlay", "Keyless Entry"],
    imageTags: ["Verified", "Hot Deal"],
    reasonsToBuy: "Full service record from official dealer, non-flood guarantee, single owner.",
    address: "Bangkok, Thailand",
    lat: 13.6678,
    lng: 100.6234,
    lineId: "@wowcardealer",
    videoUrl: "https://youtube.com/watch?v=demo",
    description: "Pristine condition 2023 Honda Civic RS Turbo. Low mileage, single owner, zero accidents.",
    descriptions: {
      thai: "สภาพนางฟ้า ไมล์น้อย มือเดียว ไม่เคยมีอุบัติเหตุ ตรวจเช็คสภาพแล้ว 210 จุด",
      english: "Pristine condition 2023 Honda Civic RS Turbo. Low mileage, single owner, zero accidents.",
      chinese: "全新状态 2023 本田 Civic RS Turbo。低里程，单一手车主，无事故记录。"
    },
    images: [
      { attachment_id: 52601, url: "https://images.unsplash.com/photo-1590362891991-f776e747a588?w=800&auto=format&fit=crop&q=80" },
      { attachment_id: 52602, url: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80" }
    ]
  },
  {
    listingId: "51980",
    title: "2024 Mercedes-Benz C220d AMG Line",
    make: "Mercedes-Benz",
    model: "C-Class",
    price: 2490000,
    formattedPrice: "฿2,490,000",
    status: "Publish",
    publishedDate: "2026-08-13",
    imageUrl: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?w=800&auto=format&fit=crop&q=80",
    featured: false,
    referenceCode: "REF-BENZ-88",
    year: 2024,
    mileage: 12000,
    modelSpecific: "C220d AMG Line",
    bodyStyle: "Sedan",
    fuelType: "Diesel",
    transmission: "Automatic",
    drivetrain: "RWD",
    color: "Black",
    engineSize: "2.0L",
    doorCount: "4",
    safetyFeatures: ["ABS", "Airbags", "360 Camera", "Active Brake Assist"],
    comfortFeatures: ["Burmester Sound", "Ambient Lighting", "Memory Seats"],
    imageTags: ["Certified Pre-Owned"],
    description: "2024 Mercedes-Benz C220d AMG Line. Official warranty until 2027.",
  },
  {
    listingId: "51975",
    title: "2022 Toyota Fortuner 2.8 Legender 4WD",
    make: "Toyota",
    model: "Fortuner",
    price: 1350000,
    formattedPrice: "฿1,350,000",
    oldPrice: 1420000,
    status: "Publish",
    publishedDate: "2026-08-08",
    imageUrl: "https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?w=800&auto=format&fit=crop&q=80",
    featured: false,
    referenceCode: "REF-TOY-55",
    year: 2022,
    mileage: 48000,
    modelSpecific: "2.8 Legender 4WD",
    bodyStyle: "SUV",
    fuelType: "Diesel",
    transmission: "Automatic",
    drivetrain: "4WD",
    color: "White",
    engineSize: "2.8L",
    doorCount: "5",
  },
  {
    listingId: "51940",
    title: "2023 BMW 330e M Sport (G20)",
    make: "BMW",
    model: "3 Series",
    price: 1890000,
    formattedPrice: "฿1,890,000",
    status: "Publish",
    publishedDate: "2026-08-05",
    imageUrl: "https://images.unsplash.com/photo-1555215695-3004980ad54e?w=800&auto=format&fit=crop&q=80",
    featured: true,
    featuredExpire: "2026-11-30",
    referenceCode: "REF-BMW-330",
    year: 2023,
    mileage: 28000,
    modelSpecific: "330e M Sport (G20)",
    bodyStyle: "Sedan",
    fuelType: "Plug-in Hybrid",
    transmission: "Automatic",
    drivetrain: "RWD",
    color: "Blue",
    engineSize: "2.0L",
    doorCount: "4",
  },
];

export const MOCK_MAKES: MakeAlert[] = [
  { id: "1", make: "Honda", followers: 1245, notificationsSent: 142, lastAlert: "2 hours ago", enabled: true },
  { id: "2", make: "Toyota", followers: 923, notificationsSent: 118, lastAlert: "5 hours ago", enabled: true },
  { id: "3", make: "Mercedes-Benz", followers: 657, notificationsSent: 84, lastAlert: "1 day ago", enabled: true },
  { id: "4", make: "BMW", followers: 589, notificationsSent: 76, lastAlert: "3 days ago", enabled: true },
  { id: "5", make: "Mazda", followers: 412, notificationsSent: 35, lastAlert: "4 days ago", enabled: true },
];

export const MOCK_MODELS: ModelAlert[] = [
  { id: "1", make: "Honda", model: "Civic", followers: 682, notificationsSent: 68, lastAlert: "2 hours ago", enabled: true },
  { id: "2", make: "Toyota", model: "Yaris Ativ", followers: 512, notificationsSent: 42, lastAlert: "1 day ago", enabled: true },
  { id: "3", make: "Mercedes-Benz", model: "C-Class", followers: 390, notificationsSent: 31, lastAlert: "1 day ago", enabled: true },
  { id: "4", make: "BMW", model: "3 Series", followers: 340, notificationsSent: 28, lastAlert: "3 days ago", enabled: true },
];

export const MOCK_AUTOMATION: AutomationRule[] = [
  {
    id: "1",
    name: "Price Drop Alerts",
    type: "price_drop",
    status: "active",
    description: "Notify users when the price of a favourited vehicle decreases beyond their configured threshold (default: ฿10,000 or 2%).",
    lastTriggered: "14 mins ago",
    notificationsGenerated: 1420,
    failedJobs: 3,
  },
  {
    id: "2",
    name: "New Arrival Alerts",
    type: "new_arrival",
    status: "active",
    description: "Notify eligible app users when a brand-new vehicle listing is published for the first time. Ignores edits to existing listings.",
    lastTriggered: "5 hours ago",
    notificationsGenerated: 3420,
    failedJobs: 12,
  },
  {
    id: "3",
    name: "Make & Model Targeted Alerts",
    type: "make_model_alerts",
    status: "active",
    description: "Automatically dispatch instant push alerts to registered users who follow specific vehicle makes or models.",
    lastTriggered: "2 hours ago",
    notificationsGenerated: 980,
    failedJobs: 1,
  },
  {
    id: "4",
    name: "Favourite Updates & Price Changes",
    type: "favourite_updates",
    status: "planned",
    description: "Send status updates when saved vehicles change availability status (e.g. Reserved, Sold, Price Restocked).",
    lastTriggered: "Never",
    notificationsGenerated: 0,
    failedJobs: 0,
  },
];

export const MOCK_QUEUE_JOBS: QueueJob[] = [
  {
    queueId: "1",
    type: "price_drop",
    listingId: "51962",
    status: "sent",
    attempts: 1,
    recipients: 420,
    created: "2026-08-13 14:20:00",
    sentAt: "2026-08-13 14:20:12",
    payload: {
      action: "price_drop",
      listing_id: "51962",
      old_price: 1039000,
      new_price: 989000,
      diff: 50000,
      onesignal_app_id: "99a802-wowcar-app-id",
    },
  },
  {
    queueId: "2",
    type: "new_arrival",
    listingId: "51980",
    status: "sent",
    attempts: 1,
    recipients: 9482,
    created: "2026-08-13 11:00:00",
    sentAt: "2026-08-13 11:00:45",
    payload: {
      action: "new_arrival",
      listing_id: "51980",
      first_publish_marker: true,
      image_key: "listivo_145",
    },
  },
  {
    queueId: "3",
    type: "make_alert",
    listingId: "51975",
    status: "pending",
    attempts: 0,
    recipients: 923,
    created: "2026-08-13 16:30:00",
    payload: {
      type: "vehicle",
      audience: "Make Followers · Toyota",
      audienceType: "make_followers",
      makeIds: [2],
      targetMake: "Toyota",
      listing_id: "51975",
    },
  },
  {
    queueId: "4",
    type: "promotion",
    status: "failed",
    attempts: 3,
    recipients: 150,
    created: "2026-08-13 09:12:00",
    failureReason: "OneSignal API Timeout (504 Gateway Timeout)",
    payload: {
      action: "promo_push",
      segment: "Inactive Users",
      error_code: 504,
    },
  },
];
